# -*- coding: utf-8 -*-
"""ALFIDO_TASK4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wIW0-fVOMhiNM-YdvhEFbIgO9uz6aJo

# Fairness, Bias and Explainability Analysis of COMPAS Recidivism Prediction Model

## Objective
The objective of this project is to analyze the fairness, bias, and explainability of a machine learning model trained on the COMPAS recidivism dataset.

The project focuses on:
- Feature importance analysis
- Explainable AI using SHAP and LIME
- Bias detection across sensitive groups such as race and gender
- Fairness metric evaluation
- Practical bias mitigation recommendations

## Dataset
COMPAS Recidivism Dataset (ProPublica)

## Techniques Used
- XGBoost Classifier
- SHAP
- LIME
- Fairlearn
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from catboost import CatBoostClassifier

import shap

from lime.lime_tabular import LimeTabularExplainer

from fairlearn.metrics import demographic_parity_difference
from fairlearn.metrics import equalized_odds_difference

import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv"

df = pd.read_csv(url)

df.head()

"""# Dataset Description

The COMPAS dataset contains criminal defendant information used for recidivism prediction.

## Target Variable

- two_year_recid
    - 1 → Reoffended within 2 years
    - 0 → Did not reoffend

## Sensitive Attributes

- Race
- Sex

## Important Features

- Age
- Prior crimes
- Charge degree
- COMPAS risk scores
"""

columns = [
    'age',
    'sex',
    'race',
    'age_cat',
    'priors_count',
    'juv_fel_count',
    'juv_misd_count',
    'juv_other_count',
    'c_charge_degree',
    'decile_score',
    'v_decile_score',
    'score_text',
    'v_score_text',
    'two_year_recid'
]

df = df[columns]

df.head()

df = df.dropna()

print(df.isnull().sum())

X = df.drop('two_year_recid', axis=1)

y = df['two_year_recid']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

categorical_features = [
    'sex',
    'race',
    'age_cat',
    'c_charge_degree',
    'score_text',
    'v_score_text'
]

model = CatBoostClassifier(
    iterations=1500,
    depth=10,
    learning_rate=0.03,
    loss_function='Logloss',
    eval_metric='Accuracy',
    random_seed=42,
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=categorical_features
)

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Final Accuracy:", accuracy)

"""## Model Performance

The CatBoost model achieved approximately 67% prediction accuracy on the COMPAS dataset.

This level of accuracy is reasonable because criminal recidivism prediction is a complex real-world problem influenced by uncertain human behavior and historical criminal justice data.

The primary goal of this project is not only predictive performance, but also fairness evaluation, bias detection, and explainable AI analysis.

Therefore, techniques such as SHAP, LIME, and fairness metrics were used to ensure transparency and ethical assessment of the model.
"""

print(classification_report(y_test, predictions))

cm = confusion_matrix(y_test, predictions)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Greens'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

importance = model.feature_importances_

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

feature_importance

plt.figure(figsize=(10,6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=feature_importance
)

plt.title("Feature Importance")

plt.show()

"""# SHAP Explainability

SHAP (SHapley Additive exPlanations) explains how each feature contributes to the model prediction.
"""

import shap

import shap

explainer = shap.Explainer(model)

shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

shap.plots.waterfall(shap_values[0])

"""## SHAP Interpretation

The SHAP summary plot shows that features such as:
- decile_score
- priors_count
- v_decile_score
- score_text

have the strongest influence on model predictions.

Higher prior crimes and higher COMPAS risk scores generally increase the probability of predicting recidivism.

# LIME Explainability

LIME explains individual predictions locally by approximating model behavior around a single prediction.
"""

X_train_lime = X_train.copy()
X_test_lime = X_test.copy()

from sklearn.preprocessing import LabelEncoder

categorical_cols = [
    'sex',
    'race',
    'age_cat',
    'c_charge_degree',
    'score_text',
    'v_score_text'
]

for col in categorical_cols:

    le = LabelEncoder()

    X_train_lime[col] = le.fit_transform(X_train_lime[col])

    X_test_lime[col] = le.transform(X_test_lime[col])

from lime.lime_tabular import LimeTabularExplainer



lime_explainer = LimeTabularExplainer(
    training_data=np.array(X_train_lime),
    feature_names=X.columns,
    class_names=['No Recidivism', 'Recidivism'],
    mode='classification'
)

def predict_fn(data):

    df = pd.DataFrame(data, columns=X.columns)

    categorical_cols = [
        'sex',
        'race',
        'age_cat',
        'c_charge_degree',
        'score_text',
        'v_score_text'
    ]

    for col in categorical_cols:
        df[col] = df[col].astype(str)

    return model.predict_proba(df)

explanation = lime_explainer.explain_instance(
    X_test_lime.iloc[0],
    predict_fn
)

explanation = lime_explainer.explain_instance(
    X_test_lime.iloc[0],
    predict_fn
)

explanation.show_in_notebook(show_table=True)

"""## LIME Interpretation

The LIME explanation highlights the most influential features contributing to the prediction for a single individual case.

Features such as:
- priors_count
- decile_score
- age

had strong influence on the model’s decision.

The explanation improves local interpretability by showing how individual feature values contribute toward predicting recidivism or non-recidivism for a specific defendant.
"""

race_groups = X_test['race'].unique()

for race in race_groups:

    idx = X_test['race'] == race

    group_accuracy = accuracy_score(
        y_test[idx],
        predictions[idx]
    )

    print(f"Race Group {race} Accuracy:", group_accuracy)

gender_groups = X_test['sex'].unique()

for gender in gender_groups:

    idx = X_test['sex'] == gender

    gender_accuracy = accuracy_score(
        y_test[idx],
        predictions[idx]
    )

    print(f"Gender Group {gender} Accuracy:", gender_accuracy)

dpd = demographic_parity_difference(
    y_true=y_test,
    y_pred=predictions,
    sensitive_features=X_test['race']
)

eod = equalized_odds_difference(
    y_true=y_test,
    y_pred=predictions,
    sensitive_features=X_test['race']
)

print("Demographic Parity Difference:", dpd)

print("Equalized Odds Difference:", eod)

"""## Ethical Considerations

The inclusion of COMPAS-generated risk scores improved prediction performance; however, these variables may already contain historical or societal bias, potentially propagating unfairness into the machine learning model.

This highlights the importance of fairness-aware machine learning, transparency, and continuous ethical evaluation in criminal justice applications.

# Bias Interpretation

## Observations

- The model achieved improved predictive performance using COMPAS-generated risk scores.
- Features such as decile_score and score_text strongly influenced predictions.
- Accuracy varied across demographic groups.
- Sensitive demographic information may indirectly affect model behavior.

## Ethical Concern

The use of historical criminal justice data and COMPAS-generated scores may propagate societal or historical bias into machine learning predictions.

# Bias Mitigation Recommendations

## 1. Balanced Dataset

Use balanced demographic representation during training.

## 2. Remove Proxy Variables

Some features may indirectly encode sensitive demographic information.

## 3. Fairness-Aware Training

Use fairness-aware methods such as:
- Reweighing
- Adversarial debiasing
- Fairlearn mitigation techniques

## 4. Human Oversight

Human experts should review predictions before judicial decisions are made.

## 5. Continuous Monitoring

Machine learning systems should be regularly audited for fairness and bias.
"""

age = int(input("Enter age: "))
sex = int(input("Enter sex (0=Female, 1=Male): "))
race = int(input("Enter race value: "))
age_cat = int(input("Enter age category value: "))
priors_count = int(input("Enter prior crimes count: "))
juv_fel_count = int(input("Enter juvenile felony count: "))
juv_misd_count = int(input("Enter juvenile misdemeanor count: "))
juv_other_count = int(input("Enter other juvenile crimes count: "))
c_charge_degree = int(input("Enter charge degree value: "))
decile_score = int(input("Enter decile score: "))
v_decile_score = int(input("Enter violent decile score: "))
score_text = int(input("Enter score text value: "))
v_score_text = int(input("Enter violent score text value: "))

sample = [[
    age,
    sex,
    race,
    age_cat,
    priors_count,
    juv_fel_count,
    juv_misd_count,
    juv_other_count,
    c_charge_degree,
    decile_score,
    v_decile_score,
    score_text,
    v_score_text
]]

prediction = model.predict(sample)

probability = model.predict_proba(sample)

print("\nPrediction:", prediction)

print("\nPrediction Probability:", probability)

if prediction[0] == 1:
    print("\nLikely to reoffend within 2 years")
else:
    print("\nNot likely to reoffend")

print(df['race'].unique())

print(df['age_cat'].unique())

print(df['score_text'].unique())

print(df[['race']].drop_duplicates())

"""**GRAPHS**"""

plt.figure(figsize=(6,5))

sns.countplot(x=y)

plt.title("Class Distribution")
plt.xlabel("Two Year Recidivism")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(8,5))

sns.countplot(x=df['race'])

plt.title("Race Distribution")
plt.xlabel("Race")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(6,5))

sns.countplot(x=df['sex'])

plt.title("Gender Distribution")
plt.xlabel("Sex")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(12,8))

numeric_df = df.select_dtypes(include=['int64', 'float64'])

corr = numeric_df.corr()

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title("Correlation Heatmap")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['priors_count'], bins=20)

plt.title("Distribution of Prior Crimes")
plt.xlabel("Prior Crimes Count")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['age'], bins=20)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")

plt.show()

race_accuracy = []

race_groups = X_test['race'].unique()

for race in race_groups:

    idx = X_test['race'] == race

    acc = accuracy_score(
        y_test[idx],
        predictions[idx]
    )

    race_accuracy.append(acc)

plt.figure(figsize=(8,5))

plt.bar(race_groups, race_accuracy)

plt.title("Accuracy by Race")
plt.xlabel("Race")
plt.ylabel("Accuracy")

plt.show()

gender_accuracy = []

gender_groups = X_test['sex'].unique()

for gender in gender_groups:

    idx = X_test['sex'] == gender

    acc = accuracy_score(
        y_test[idx],
        predictions[idx]
    )

    gender_accuracy.append(acc)

plt.figure(figsize=(6,5))

plt.bar(gender_groups, gender_accuracy)

plt.title("Accuracy by Gender")
plt.xlabel("Gender")
plt.ylabel("Accuracy")

plt.show()

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar"
)

shap.plots.scatter(
    shap_values[:, "priors_count"]
)

shap.plots.bar(shap_values)

top_features = feature_importance.head(5)

plt.figure(figsize=(8,8))

plt.pie(
    top_features['Importance'],
    labels=top_features['Feature'],
    autopct='%1.1f%%'
)

plt.title("Top 5 Feature Importance")

plt.show()

from sklearn.metrics import roc_curve, auc

probs = model.predict_proba(X_test)[:,1]

fpr, tpr, thresholds = roc_curve(y_test, probs)

roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))

plt.plot(fpr, tpr, label='AUC = %0.2f' % roc_auc)

plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.title('ROC Curve')

plt.legend()

plt.show()

"""## ROC Curve Analysis

The ROC curve evaluates the model’s discrimination capability between recidivism and non-recidivism cases.

A higher AUC value indicates better classification performance.

# Conclusion

This project analyzed fairness, bias, and explainability in the COMPAS recidivism prediction system using machine learning techniques.

A CatBoost classifier was trained to predict two-year recidivism outcomes, achieving moderate predictive performance while enabling detailed fairness and interpretability analysis.

SHAP and LIME explanations improved model transparency by identifying the most influential features affecting predictions.

The analysis also revealed potential fairness concerns across demographic groups, emphasizing the importance of ethical AI practices in sensitive criminal justice applications.

This study demonstrates that high predictive performance alone is insufficient in socially sensitive domains where fairness, accountability, and transparency are equally important.
"""